In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('crop.csv')
data

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [ ]:
x=data.iloc[:,:7].values
x

array([[ 90.        ,  42.        ,  43.        , ...,  82.00274423,
          6.50298529, 202.9355362 ],
       [ 85.        ,  58.        ,  41.        , ...,  80.31964408,
          7.03809636, 226.6555374 ],
       [ 60.        ,  55.        ,  44.        , ...,  82.3207629 ,
          7.84020714, 263.9642476 ],
       ...,
       [118.        ,  33.        ,  30.        , ...,  67.22512329,
          6.36260785, 173.3228386 ],
       [117.        ,  32.        ,  34.        , ...,  52.12739421,
          6.75879255, 127.1752928 ],
       [104.        ,  18.        ,  30.        , ...,  60.39647474,
          6.77983261, 140.9370415 ]])

In [ ]:
y=data.iloc[:,-1].values
y

array(['rice', 'rice', 'rice', ..., 'coffee', 'coffee', 'coffee'],
      dtype=object)

In [ ]:
!pip install scikit-learn

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)

In [9]:
X_train

array([[ 57.        ,  68.        ,  81.        , ...,  17.30457712,
          8.08109526,  72.78624223],
       [ 40.        ,  24.        ,  25.        , ...,  50.44030129,
          5.44500842,  95.8946444 ],
       [  5.        ,  13.        ,  37.        , ...,  89.7870345 ,
          5.64824365, 103.3183074 ],
       ...,
       [ 13.        ,  72.        ,  21.        , ...,  21.0278674 ,
          5.82119449,  60.27552528],
       [ 37.        ,  79.        ,  19.        , ...,  69.3478631 ,
          7.14394276,  69.40878198],
       [107.        ,   5.        ,  52.        , ...,  89.98405233,
          6.88142575,  57.40847165]])

In [10]:
X_test

array([[ 16.        , 139.        , 203.        , ...,  80.96093443,
          6.27564088,  65.84748763],
       [ 78.        ,  40.        ,  38.        , ...,  83.85642678,
          7.54987368, 248.2256491 ],
       [ 21.        ,   9.        ,  40.        , ...,  90.64498715,
          5.95640183, 105.6209954 ],
       ...,
       [ 87.        ,  38.        ,  29.        , ...,  57.88370456,
          6.65264258, 156.1457255 ],
       [113.        ,  38.        ,  20.        , ...,  78.58320116,
          6.36472993,  74.94136567],
       [107.        ,  10.        ,  49.        , ...,  89.00481725,
          6.75519203,  45.24690619]])

In [11]:
from sklearn import linear_model
from sklearn.metrics import accuracy_score

In [12]:
reg=linear_model.LogisticRegression()
reg.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [14]:
ypred=reg.predict(X_test)
acc=accuracy_score(Y_test,ypred)
acc=acc*100
acc

97.04545454545455

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,Y_train)


KNeighborsClassifier(n_neighbors=1)

In [18]:
knnpred=knn.pred(X_test)
acc1=accuracy_score(Y_test,knnpred)
acc1=acc1*100\
acc1

98.18181818181819